services:
  pm_mysql:
    image: mysql:8.0
    container_name: pm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pm_saas
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pm_mysql_data:/var/lib/mysql

volumes:
  pm_mysql_data:
