"""sync database schema with latest models

Revision ID: 2f290d3b5ee1
Revises: df0fe3c8aa25
Create Date: 2026-03-11 13:51:17.261859

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f290d3b5ee1"
down_revision: Union[str, None] = "df0fe3c8aa25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column(
            "type",
            sa.Enum("info", "alert", "billing", "system", name="notificationtype"),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notifications_user_created",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_user_read",
        "notifications",
        ["user_id", "is_read"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        "ix_refresh_user_active",
        "refresh_tokens",
        ["user_id", "is_revoked"],
        unique=False,
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix-team-owner-created", "teams", ["owner_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=True)
    op.create_table(
        "team_invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("invited_user_id", sa.Integer(), nullable=False),
        sa.Column("invited_email", sa.String(length=255), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("info", "alert", "billing", name="teaminvitationstatus"),
            nullable=False,
        ),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["invited_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id", "invited_email", "status", name="uq_team_pending_invitation"
        ),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        "ix_team_invitation_email_status",
        "team_invitations",
        ["invited_email", "status"],
        unique=False,
    )
    op.create_table(
        "team_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("owner", "member", name="teammemberrole"), nullable=False
        ),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "user_id", name="uq_team_member"),
    )
    op.create_index(
        "ix_team_members_team_user",
        "team_members",
        ["team_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "project_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("created", "updated", "deleted", name="action"),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_project_activity_project_time",
        "project_activities",
        ["project_id", "timestamp"],
        unique=False,
    )
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.add_column("projects", sa.Column("team_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.create_index("ix_projects_team_id", "projects", ["team_id"], unique=False)
    op.create_foreign_key(
        None, "projects", "teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "subscriptions", sa.Column("provider", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "subscriptions",
        sa.Column("razorpay_order_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "subscriptions",
        sa.Column("razorpay_payment_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "subscriptions",
        sa.Column("razorpay_subscription_id", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_subscriptions_razorpay_order_id"),
        "subscriptions",
        ["razorpay_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_razorpay_payment_id"),
        "subscriptions",
        ["razorpay_payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_razorpay_subscription_id"),
        "subscriptions",
        ["razorpay_subscription_id"],
        unique=False,
    )
    op.create_index("ix_users_verified", "users", ["email_verified"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_verified", table_name="users")
    op.drop_index(
        op.f("ix_subscriptions_razorpay_subscription_id"), table_name="subscriptions"
    )
    op.drop_index(
        op.f("ix_subscriptions_razorpay_payment_id"), table_name="subscriptions"
    )
    op.drop_index(
        op.f("ix_subscriptions_razorpay_order_id"), table_name="subscriptions"
    )
    op.drop_column("subscriptions", "razorpay_subscription_id")
    op.drop_column("subscriptions", "razorpay_payment_id")
    op.drop_column("subscriptions", "razorpay_order_id")
    op.drop_column("subscriptions", "provider")
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_index("ix_projects_team_id", table_name="projects")
    op.create_index(
        op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False
    )
    op.drop_column("projects", "team_id")
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"),
        "audit_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.drop_index("ix_project_activity_project_time", table_name="project_activities")
    op.drop_table("project_activities")
    op.drop_index("ix_team_members_team_user", table_name="team_members")
    op.drop_table("team_members")
    op.drop_index("ix_team_invitation_email_status", table_name="team_invitations")
    op.drop_table("team_invitations")
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_index("ix-team-owner-created", table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_refresh_user_active", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_notifications_user_read", table_name="notifications")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
